"""Critters: small upright chibi animals (the fox and capybara are side-on, in dogs_cats)."""

from __future__ import annotations

from .build import biped
from .rig import Part, v

biped(
    "bunny",
    "Bunny",
    "critters",
    "A round white bunny with tall pink-lined ears.",
    slots={"fur": (245, 245, 255), "inner": (255, 120, 170), "belly": (255, 220, 235)},
    key={"w": "fur", "W": "fur*0.75", "p": "inner", "b": "belly", "c": "fur", "n": "fur", "f": "fur*0.8"},
    head=(
        "..ww..ww..",
        "..wp..wp..",
        "..wp..wp..",
        "..wp.wwp..",
        ".wwwwwwww.",
        "wwwwwwwwww",
        "wwwwwwwwww",
        "wwwwwwwwww",
        "wwpwwwwwpw",
        ".wwwwwwww.",
        "..WWWWWW..",
    ),
    torso=("wbbbbw", "wbbbbw", "Wwwwww"),
    torso_xy=(5, 11),
    eyes={"pts": [(8, 6), (11, 6)], "w": 1, "h": 2},
    limbs="nub",
    arms_xy=(11, 3, 11),
    feet_xy=(5, 14),
    mouth=(10, 8),
    opts={"food": "carrot", "sit_drop": 1},
    squash_row=11,
    lap=(8, 12),
)

biped(
    "hamster",
    "Hamster",
    "critters",
    "A pocket hamster with stuffed cream cheeks and tiny round ears.",
    slots={"body": (255, 150, 50), "cream": (255, 238, 205), "feet": (255, 150, 170)},
    key={"o": "body", "c": "cream", "i": "feet", "C": "cream*0.8", "n": "feet", "f": "feet"},
    head=(
        ".oo....oo.",
        ".oioooooio",
        ".oooooooo.",
        "oooooooooo",
        "oooooooooo",
        "occoooocco",
        "cccccccccc",
        ".cccccccc.",
    ),
    head_xy=(3, 3),
    torso=("cccccccc", "cccccccc", ".CCCCCC."),
    torso_xy=(4, 11),
    eyes={"pts": [(7, 7), (10, 7)], "w": 1, "h": 2},
    limbs="nub",
    arms_xy=(11, 3, 11),
    feet_xy=(5, 14),
    mouth=(9, 10),
    opts={"food": "cookie", "sit_drop": 1},
    squash_row=12,
    lap=(8, 12),
)

biped(
    "panda",
    "Panda",
    "critters",
    "A roly-poly panda with dark eye patches and a bamboo habit.",
    slots={"white": (245, 245, 250), "dark": (64, 64, 80), "eyes": (255, 255, 255)},
    key={"w": "white", "d": "dark", "c": "dark", "n": "dark", "f": "dark", "e": "eyes", "k": "#0c0c12"},
    head=(
        "dd......dd",
        "ddwwwwwwdd",
        ".wwwwwwww.",
        "wwwwwwwwww",
        "wddwwwwddw",
        "wdddwwdddw",
        "wwddwkwddw",
        ".wwwwwwww.",
    ),
    head_xy=(3, 1),
    torso=("dwwwwwwd", "dwwwwwwd", "dwwwwwwd", "ddwwwwdd"),
    torso_xy=(4, 9),
    eyes={"pts": [(6, 5), (11, 5)], "w": 1, "h": 1, "lid": "e"},
    limbs="nub",
    arms_xy=(12, 2, 9),
    feet_xy=(5, 13),
    mouth=(9, 7),
    opts={"food": "bamboo", "sit_drop": 1},
    squash_row=11,
    lap=(8, 12),
)

biped(
    "penguin",
    "Penguin",
    "critters",
    "A waddly penguin: navy coat, white tummy, orange beak and feet.",
    slots={"coat": (40, 70, 170), "belly": (245, 245, 255), "beak": (255, 150, 0)},
    key={"b": "coat", "w": "belly", "y": "beak", "c": "coat", "n": "coat", "f": "beak"},
    head=(
        "..bbbbbb..",
        ".bbbbbbbb.",
        "bbbwwwwbbb",
        "bbwwwwwwbb",
        "bbwwwwwwyy",
        "bbwwwwwwyb",
        ".bwwwwwwb.",
    ),
    head_xy=(3, 2),
    torso=("bwwwwwwb", "bwwwwwwb", "bwwwwwwb", "bwwwwwwb", ".bbbbbb."),
    torso_xy=(4, 9),
    eyes={"pts": [(7, 5), (10, 5)], "w": 1, "h": 2},
    limbs="nub",
    arms_xy=(12, 2, 9),
    feet_xy=(5, 14),
    opts={"food": "fish", "sit_drop": 1},
    squash_row=11,
)

biped(
    "frog",
    "Frog",
    "critters",
    "A cheerful green frog with bulging eyes and a wide grin.",
    slots={"skin": (70, 210, 60), "belly": (230, 250, 170), "mouth": (20, 100, 20)},
    key={"g": "skin", "G": "skin*0.7", "y": "belly", "m": "mouth", "c": "skin", "n": "skin", "f": "skin*0.8"},
    head=(
        ".gg....gg.",
        "gWWg..gWWg",
        "gWWggggWWg",
        "gggggggggg",
        "gggggggggg",
        "gmmmmmmmmg",
        ".gggggggg.",
    ),
    head_xy=(3, 2),
    torso=("gyyyyyyg", "gyyyyyyg", "Ggyyyyg."),
    torso_xy=(4, 9),
    eyes={"pts": [(5, 3), (11, 3)], "w": 1, "h": 2},
    limbs="nub",
    arms_xy=(12, 2, 9),
    feet_xy=(4, 12),
    legs={
        "stand": v("ff....ff", "fff..fff"),
        "walk_a": v("ff....ff", "fff...fff"),
        "walk_b": v("ff....ff", ".fff.fff"),
        "run_a": v("ff.....ff", ".......ff", ox=-1),
        "run_b": v(".ff..ff."),
        "crouch": v("fffffff.", "ffff.fff"),
        "sit": v("ffffffff", "fff..fff"),
        "tuck": v("ff....ff"),
        "kick_back": v("ff..ff", "ff.ff"),
        "kick_fwd": v("ff....ff", "fff....fff"),
    },
    mouth=(11, 7),
    opts={"food": "leaf", "sit_drop": 1},
    squash_row=10,
)

biped(
    "duck",
    "Duckling",
    "critters",
    "A fluffy yellow duckling with an orange bill.",
    slots={"down": (255, 225, 20), "bill": (255, 130, 0), "wing": (230, 180, 0)},
    key={"y": "down", "o": "bill", "w": "wing", "c": "wing", "n": "wing", "f": "bill"},
    head=(
        "..yyyy....",
        ".yyyyyy...",
        "yyyyyyyy..",
        "yyyyyyyooo",
        "yyyyyyyoo.",
        ".yyyyyy...",
    ),
    head_xy=(4, 1),
    torso=("..yyyyyy..", ".yyyyyyyy.", "yyyyyyyyyy", "yyyyyyyyyy", ".yyyyyyyy.", "..yyyyyy.."),
    torso_xy=(2, 7),
    eyes={"pts": [(10, 3)], "w": 1, "h": 2},
    limbs="nub",
    arms_xy=(10, 3, 9),
    feet_xy=(5, 13),
    parts={
        "tail": Part(
            0, 8, {"default": v("yy", "y."), "b": v(".y", "yy"), "down": v("..", "yy")}, parent="body", z=0
        )
    },
    opts={"food": "leaf", "sit_drop": 1},
    squash_row=10,
    lap=(7, 12),
)

biped(
    "axolotl",
    "Axolotl",
    "critters",
    "A smiley pink axolotl with frilly magenta gills.",
    slots={"skin": (255, 150, 190), "gills": (255, 40, 140), "belly": (255, 205, 225)},
    key={"p": "skin", "m": "gills", "b": "belly", "c": "skin", "n": "skin", "f": "skin*0.8", "k": "#50142d"},
    head=(
        "m.m......m.m",
        ".mpppppppppm",
        "mpppppppppp.",
        ".pppppppppm.",
        "mpppppppppp.",
        ".pppkkkkppm.",
        "..pppppppp..",
    ),
    head_xy=(2, 2),
    torso=("pbbbbbbp", "pbbbbbbp", ".pppppp."),
    torso_xy=(4, 9),
    eyes={"pts": [(6, 5), (11, 5)], "w": 1, "h": 1},
    limbs="nub",
    arms_xy=(12, 2, 9),
    feet_xy=(5, 12),
    parts={
        "tail": Part(
            0,
            9,
            {
                "default": v("..pp", "pppp", "pp.."),
                "b": v("pp..", "pppp", "..pp"),
                "down": v("....", "pppp", "pp.."),
            },
            parent="body",
            z=0,
        )
    },
    opts={"food": "leaf", "sit_drop": 1},
    squash_row=10,
    lap=(8, 11),
)
