"""Troops: fantasy-arena heroes (original chibi archetypes, not copies of any game's sprites)."""

from __future__ import annotations

from .build import biped
from .parts import ROBE
from .rig import Part, V, v

SKIN = (255, 190, 140)
ATK = ("attack",)


def _tint(d: dict[str, V], a: str, b: str) -> dict[str, V]:
    return {k: V(tuple(r.replace(a, b) for r in x.rows), x.ox, x.oy, x.hand, x.grip) for k, x in d.items()}


SWORD = {
    "down": v(".W.", ".W.", ".w.", ".w.", "yyy", ".u.", grip=(0, 5)),
    "up": v(".W.", ".W.", ".w.", ".w.", "yyy", ".u.", grip=(1, 5)),
    "fwd": v(".y...", "uywwW", ".y...", grip=(0, 1)),
    "out": v("u...", "yw..", "..w.", "...W", grip=(0, 0)),
    "aim": v(".y...", "uywwW", ".y...", grip=(0, 1)),
}
DAGGER = {
    "down": v("W", "w", "y", "u", grip=(0, 3)),
    "up": v("W", "w", "y", "u", grip=(0, 3)),
    "fwd": v(
        "uyW",
    ),
    "out": v("u..", ".y.", "..W"),
}
BOW = {
    "down": v(".u", "uW", "uW", "uW", ".u", grip=(0, 2)),
    "aim": v(".u", "uW", "uW", "uW", ".u", grip=(0, 2)),
}
STAFF = {
    "down": v(".o.", "oOo", ".o.", ".u.", ".u.", ".u.", ".u.", ".u.", grip=(1, 6)),
    "up": v(".o.", "oOo", ".o.", ".u.", ".u.", ".u.", ".u.", ".u.", grip=(1, 5)),
    "wave": v(".o.", "oOo", ".o.", ".u.", ".u.", ".u.", ".u.", ".u.", grip=(1, 5)),
    "fwd": v("....o", "uuuuOo", "....o", grip=(0, 1)),
}
MACE = {
    "down": v("G.G", "GGG", "G.G", ".u.", ".u.", grip=(1, 4)),
    "up": v("G.G", "GGG", "G.G", ".u.", ".u.", grip=(1, 4)),
    "fwd": v("....G", "uuGGG", "....G", grip=(0, 1)),
    "out": v("u...", ".u..", "..GG", "..GG", grip=(0, 0)),
}
SCEPTER = {
    "down": v(".y.", "yry", ".y.", ".y.", ".y.", grip=(1, 4)),
    "up": v(".y.", "yry", ".y.", ".y.", ".y.", grip=(1, 4)),
    "fwd": v("...y", "yyyr", "...y", grip=(0, 1)),
}

biped(
    "knight",
    "Knight",
    "troops",
    "A brave little knight: steel helmet with a red plume, blue tabard, sword and shield.",
    slots={
        "armor": (170, 180, 200),
        "tabard": (30, 90, 255),
        "plume": (255, 30, 40),
        "skin": SKIN,
        "trim": (255, 200, 0),
    },
    key={
        "g": "armor",
        "G": "armor*0.55",
        "r": "plume",
        "s": "skin",
        "t": "tabard",
        "T": "tabard*0.6",
        "y": "trim",
        "u": "#6e3c1e",
        "w": "#dce6f0",
        "c": "armor",
        "n": "armor*0.7",
        "p": "armor*0.6",
        "f": "#3c3c50",
        "a": "armor",
    },
    head=(
        "....rrr...",
        "..ggggrr..",
        ".gWggggggg",
        "gggggggggg",
        "gGGsssssgg",
        "gGssssssgg",
        "ggGsssssgg",
        ".gggggggg.",
    ),
    torso=("GattttaG", "GattytaG", "GattttaG", "uuuyuuuu", "GaTTTTaG"),
    eyes={"pts": [(7, 4), (10, 4)], "w": 1, "h": 2},
    item=SWORD,
    parts={
        "shield": Part(
            0,
            0,
            {"default": v(".yyy.", "ytttty", "yttyty", "ytttty", ".ytty.", "..yy.", grip=(3, 2))},
            parent="arm_l",
            z=2,
            attach="arm_l",
        ),
    },
    opts={"food": "drumstick", "attack": "melee"},
    extras=ATK,
)

biped(
    "archer",
    "Archer",
    "troops",
    "A sharp-eyed archer in a green hood, pink braid peeking out, bow at the ready.",
    slots={
        "hood": (40, 170, 70),
        "hair": (255, 70, 160),
        "tunic": (70, 210, 90),
        "skin": SKIN,
        "leather": (130, 74, 30),
    },
    key={
        "g": "hood",
        "G": "hood*0.6",
        "m": "hair",
        "s": "skin",
        "S": "skin*0.8",
        "t": "tunic",
        "T": "tunic*0.6",
        "u": "leather",
        "y": "#ffd200",
        "c": "tunic",
        "n": "skin",
        "p": "leather",
        "f": "leather*0.6",
    },
    head=(
        "...gggg...",
        "..gggggg..",
        ".gggggggg.",
        "ggmmmmmmmg",
        "gmmsssssss",
        "gmssssssss",
        "gmssssssS.",
        ".mm.ssss..",
    ),
    torso=("TttttttT", "TtttttuT", "uuuuyuuu", "TttttttT", "tttttttt"),
    eyes={"pts": [(7, 5), (10, 5)], "w": 1, "h": 2},
    item=BOW,
    parts={"quiver": Part(2, 6, {"default": v("W.", "uu", "uu", "uu", "uu")}, parent="body", z=-2)},
    opts={"food": "apple", "attack": "bow"},
    extras=ATK,
)

biped(
    "barbarian",
    "Barbarian",
    "troops",
    "A hot-headed barbarian: wild blond hair, a huge moustache, bare arms and a big sword.",
    slots={
        "hair": (255, 205, 30),
        "skin": SKIN,
        "kilt": (140, 80, 30),
        "belt": (80, 50, 20),
        "boots": (90, 60, 40),
    },
    key={
        "y": "hair",
        "s": "skin",
        "S": "skin*0.78",
        "u": "kilt",
        "U": "kilt*0.7",
        "b": "belt",
        "k": "#3c1e0a",
        "c": "skin",
        "n": "skin",
        "p": "skin*0.9",
        "f": "boots",
        "w": "#dce6f0",
        "W": "#ffffff",
        "g": "#ffd200",
    },
    head=(
        "..yyyyyy..",
        ".yyyyyyyy.",
        "yyyyyyyyyy",
        "yykkssskks",
        "yyssssssss",
        "yssyyyyyys",
        ".syy..yys.",
        "..ssssss..",
    ),
    torso=("SssssssS", "SsSssSsS", "SssssssS", "bbbgbbbb", "uuUuuUuu"),
    eyes={"pts": [(7, 4), (10, 4)], "w": 1, "h": 1},
    item=_tint(SWORD, "y", "g"),
    opts={"food": "drumstick", "attack": "melee"},
    extras=ATK,
)

biped(
    "giant",
    "Giant",
    "troops",
    "A gentle-ish giant: buzz-cut, heavy brow, patched tunic and fists like boulders.",
    slots={
        "hair": (150, 80, 30),
        "skin": (255, 180, 130),
        "tunic": (215, 175, 110),
        "belt": (110, 60, 25),
        "pants": (120, 90, 60),
    },
    key={
        "h": "hair",
        "s": "skin",
        "S": "skin*0.78",
        "o": "tunic",
        "O": "tunic*0.7",
        "u": "belt",
        "k": "#3c1e0a",
        "y": "#c8a03c",
        "c": "skin",
        "n": "skin*0.9",
        "p": "pants",
        "f": "belt*0.7",
    },
    head=(
        "..hhhhhh..",
        ".hhhhhhhh.",
        "hhhhhhhhhh",
        "hhskkskkss",
        "hsssssssss",
        "hsssssssSs",
        ".ssskkkss.",
        "..ssssss..",
    ),
    torso=("OuooooOO", "OouoooOO", "OoouoOoO", "uuuuyuuu", "OOOOOOOO"),
    eyes={"pts": [(7, 4), (10, 4)], "w": 1, "h": 1},
    arms={"arm_r": {"down": v("Cc", "Cc", "Cc", "nn", "nn", hand=(0, 3))}},
    opts={"food": "drumstick", "attack": "punch", "attack_fx": "punch"},
    extras=ATK,
)

biped(
    "goblin",
    "Goblin",
    "troops",
    "A sneaky goblin: green skin, huge pointy ears, a toothy grin and a rusty dagger.",
    slots={"skin": (90, 210, 60), "rags": (140, 90, 40), "eyes": (255, 220, 0)},
    key={
        "g": "skin",
        "G": "skin*0.65",
        "u": "rags",
        "U": "rags*0.65",
        "k": "#0c2808",
        "W": "#ffffff",
        "e": "eyes",
        "y": "#c8a03c",
        "w": "#b4b4c8",
        "c": "skin",
        "n": "skin",
        "p": "skin*0.8",
        "f": "rags*0.6",
    },
    head=(
        "...gggggg...",
        "..gggggggg..",
        "gggggggggggg",
        ".gggggggggGg",
        "..ggggggggGG",
        "..ggkWkWkg..",
        "...gggggg...",
    ),
    head_xy=(2, 1),
    torso=("UuuuuuuU", "UuUuuUuU", "UuuuuuuU", "uUuUuUuU", "U.UU.UU."),
    eyes={"pts": [(7, 3), (10, 3)], "w": 1, "h": 2},
    item=DAGGER,
    opts={"food": "drumstick", "attack": "melee"},
    extras=ATK,
)

biped(
    "wizard",
    "Wizard",
    "troops",
    "A wise old wizard: tall blue hat, snowy beard, starry robe and a glowing staff.",
    slots={
        "robe": (40, 90, 255),
        "beard": (245, 245, 255),
        "skin": SKIN,
        "glow": (0, 230, 255),
        "stars": (255, 214, 0),
    },
    key={
        "b": "robe",
        "B": "robe*0.6",
        "w": "beard",
        "h": "beard*0.8",
        "s": "skin",
        "y": "stars",
        "c": "robe",
        "n": "skin",
        "p": "robe",
        "f": "#503c28",
        "o": "glow",
        "O": "#ffffff",
        "u": "#8c5a28",
    },
    head=(
        "......bb..",
        ".....bbb..",
        "....byyb..",
        "bbbbbbbbbb",
        ".hsssssss.",
        ".hssssssss",
        ".hwwwwwwww",
        "..wwwwwww.",
    ),
    torso=("BbwwwwbB", "BbbwwbbB", "BbbbbbyB", "BbbybbbB", "bbbbbbbb"),
    eyes={"pts": [(7, 5), (10, 5)], "w": 1, "h": 1},
    legs=ROBE,
    item=STAFF,
    opts={"food": "apple", "attack": "magic", "attack_fx": "orb"},
    extras=("attack", "cast"),
)

biped(
    "skeleton",
    "Skeleton",
    "troops",
    "A rattly skeleton with hollow eyes, a clacking grin and a chipped sword.",
    slots={"bone": (235, 235, 220), "sockets": (20, 10, 30), "rust": (180, 110, 60)},
    key={
        "w": "bone",
        "W": "bone*0.7",
        "k": "#1e1428",
        "e": "sockets",
        "c": "bone",
        "n": "bone",
        "p": "bone",
        "f": "bone*0.75",
        "y": "rust",
        "u": "rust*0.6",
        "C": "bone*0.8",
    },
    head=(
        "..wwwwww..",
        ".wwwwwwww.",
        "wwwwwwwwww",
        "wwwwwwwwww",
        "wwwwwwwwww",
        "wwwwwwwkww",
        ".wkwkwkww.",
        "..wwwwww..",
    ),
    torso=("..wwww..", "w.wWWw.w", ".wwwwww.", "w.wWWw.w", "..wwww.."),
    eyes={"pts": [(6, 3), (10, 3)], "w": 2, "h": 2},
    legs={
        "stand": v(".w...w..", ".w...w..", ".ff..ff."),
        "walk_a": v(".w...w..", ".w....ff", ".ff....."),
        "walk_b": v(".w...w..", ".ff..w..", ".....ff."),
    },
    item=_tint(SWORD, "w", "W"),
    opts={"food": "drumstick", "attack": "melee"},
    extras=ATK,
)

biped(
    "mech_knight",
    "Mech Knight",
    "troops",
    "A heavy armoured knight in dark plate with a glowing visor and a spiked mace.",
    slots={"armor": (80, 80, 110), "visor": (255, 40, 200), "trim": (160, 160, 190)},
    key={
        "a": "armor",
        "A": "armor*0.55",
        "v": "visor",
        "t": "trim",
        "e": "visor",
        "k": "armor*0.3",
        "c": "armor",
        "n": "trim",
        "p": "armor*0.7",
        "f": "armor*0.45",
        "G": "trim",
        "u": "#503c28",
    },
    head=(
        ".t......t.",
        "..aaaaaa..",
        ".aaaaaaaa.",
        "aataaaaaaa",
        "aaAAAAAAAA",
        "aaaaaaaaaa",
        "aAaaaaaaaa",
        ".aaaaaaaa.",
    ),
    torso=("tAaaaaAt", "Aavvvvaa", "Aaavvaaa", "tttttttt", "AaaaaaaA"),
    eyes={"pts": [(6, 4), (10, 4)], "w": 2, "h": 1, "lid": "k"},
    item=MACE,
    opts={"food": "drumstick", "attack": "melee"},
    extras=ATK,
)

biped(
    "king",
    "King",
    "troops",
    "A jolly king: golden crown, an enormous ginger beard and a royal red cape. Great for emotes.",
    slots={
        "beard": (255, 110, 30),
        "robe": (230, 20, 40),
        "crown": (255, 210, 0),
        "skin": SKIN,
        "fur": (250, 250, 255),
    },
    key={
        "h": "beard",
        "H": "beard*0.75",
        "r": "robe",
        "R": "robe*0.6",
        "y": "crown",
        "s": "skin",
        "w": "fur",
        "b": "#1e8cff",
        "g": "#ff1e5a",
        "c": "robe",
        "n": "skin",
        "p": "robe*0.7",
        "f": "#503c28",
    },
    head=(
        ".y.y.y.y..",
        ".yyyyyyy..",
        ".ygyybyy..",
        "hhssssssh.",
        "hsssssssss",
        "hhhsssshhh",
        "hhhhhhhhhh",
        ".hhhhhhhh.",
    ),
    torso=("RhhhhhhR", "RrhhhhrR", "wwwwwwww", "RrryrrrR", "rrrrrrrr"),
    eyes={"pts": [(7, 4), (10, 4)], "w": 1, "h": 1},
    mouth=(9, 6),
    item=SCEPTER,
    parts={
        "cape": Part(
            2,
            8,
            {
                "default": v(
                    ".RRRRRRRRRR.",
                    "RRRRRRRRRRRR",
                    "RRRRRRRRRRRR",
                    "RRRRRRRRRRRR",
                    "RRRRRRRRRRRR",
                    ".RRRRRRRRRR.",
                )
            },
            parent="body",
            z=-3,
        )
    },
    opts={"food": "drumstick", "attack": "melee"},
    extras=ATK,
)

biped(
    "princess",
    "Princess",
    "troops",
    "A fearless princess: golden hair, a little tiara, a pink gown and a trusty bow.",
    slots={"hair": (255, 210, 40), "gown": (255, 90, 180), "skin": SKIN, "gem": (0, 220, 255)},
    key={
        "y": "hair",
        "Y": "hair*0.75",
        "p": "gown",
        "P": "gown*0.65",
        "s": "skin",
        "c": "gown",
        "n": "skin",
        "w": "#ffffff",
        "g": "gem",
        "f": "gown*0.5",
        "u": "#8c5a28",
        "W": "#ffffff",
    },
    head=(
        "...wgw....",
        "..yyyyyy..",
        ".yyyyyyyy.",
        "yyyyyyyyyy",
        "yyssssssss",
        "yysssssssS",
        "yyysssssy.",
        "yyy.sss...",
    ),
    torso=("YppppppY", "PppwwppP", "PppppppP", "pppppppp", "pppppppp"),
    eyes={"pts": [(7, 4), (10, 4)], "w": 1, "h": 2},
    legs=ROBE,
    item=BOW,
    opts={"food": "apple", "attack": "bow"},
    extras=ATK,
)
