"""TV & cartoon homages: original chibi archetypes that nod to well-known shows (not copies)."""

from __future__ import annotations

from .build import biped
from .parts import ROBE

SKIN = (255, 190, 140)

biped(
    "mad_scientist",
    "Mad Scientist",
    "tv",
    "A cosmically cranky scientist: spiky blue-grey hair, a unibrow, a drooly grin and a lab coat.",
    slots={
        "hair": (150, 190, 230),
        "coat": (240, 240, 250),
        "shirt": (60, 170, 255),
        "skin": (255, 205, 170),
        "pants": (130, 80, 40),
    },
    key={
        "h": "hair",
        "H": "hair*0.65",
        "s": "skin",
        "S": "skin*0.8",
        "w": "coat",
        "W": "#ffffff",
        "b": "shirt",
        "k": "hair*0.45",
        "d": "#8cdcff",
        "c": "coat",
        "n": "skin",
        "p": "pants",
        "f": "#3c2814",
    },
    head=(
        ".h.hh.h.h.",
        "hhhhhhhhhh",
        "hhhhhhhhhh",
        "hhkkkkkkkh",
        "hhsWssWsss",
        "hsssssssss",
        ".sskkkkks.",
        "..sssssd..",
    ),
    torso=("wwbbbbww", "wwbbbbww", "wwbbbbww", "wwbbbbww", "ww.pp.ww"),
    eyes={"pts": [(7, 4), (10, 4)], "w": 1, "h": 1},
    opts={"food": "apple"},
)

biped(
    "nervous_teen",
    "Nervous Teen",
    "tv",
    "An anxious teenage sidekick: brown mop of hair, wide worried eyes, yellow tee and blue jeans.",
    slots={"hair": (140, 80, 30), "shirt": (255, 220, 30), "pants": (40, 90, 220), "skin": (255, 205, 170)},
    key={
        "h": "hair",
        "H": "hair*0.65",
        "s": "skin",
        "S": "skin*0.8",
        "y": "shirt",
        "Y": "shirt*0.75",
        "k": "#50281e",
        "c": "shirt",
        "n": "skin",
        "p": "pants",
        "f": "#f0f0f0",
    },
    head=(
        "..hhhhhh..",
        ".hhhhhhhh.",
        "hhhhhhhhhh",
        "hhssssssss",
        "hsssssssss",
        "hsssssssss",
        ".ssskskss.",
        "..ssssss..",
    ),
    torso=("YyyyyyyY", "YyyyyyyY", "YyyyyyyY", "YyyyyyyY", "pppppppp"),
    eyes={"pts": [(7, 4), (10, 4)], "w": 1, "h": 2},
    opts={"food": "apple"},
)

biped(
    "crayon_kid",
    "Crayon Kid",
    "tv",
    "A cheeky five-year-old: bowl of black hair, very thick eyebrows, red shirt and yellow shorts.",
    slots={"hair": (50, 45, 60), "shirt": (255, 30, 40), "shorts": (255, 210, 0), "skin": (255, 200, 160)},
    key={
        "h": "hair",
        "s": "skin",
        "S": "skin*0.8",
        "k": "#1e1428",
        "r": "shirt",
        "R": "shirt*0.7",
        "y": "shorts",
        "c": "shirt",
        "n": "skin",
        "p": "skin",
        "f": "#f0f0f0",
    },
    head=(
        "..hhhhh...",
        ".hhhhhhhh.",
        "hhskksskks",
        "hsssssssss",
        "ssssssssss",
        "ssssssssss",
        ".sssskksss",
        "..ssssss..",
    ),
    torso=("RrrrrrrR", "RrrrrrrR", "RrrrrrrR", "yyyyyyyy", "yyyyyyyy"),
    eyes={"pts": [(7, 3), (10, 3)], "w": 1, "h": 2},
    opts={"food": "cookie"},
)

biped(
    "chem_teacher",
    "Chem Teacher",
    "tv",
    "A mild-mannered chemistry teacher gone rogue: bald, glasses, goatee and a black pork-pie hat.",
    slots={
        "hat": (70, 70, 85),
        "shirt": (120, 150, 80),
        "skin": SKIN,
        "goatee": (140, 90, 40),
        "pants": (170, 150, 110),
    },
    key={
        "k": "hat",
        "K": "hat*0.6",
        "s": "skin",
        "S": "skin*0.8",
        "G": "#28283a",
        "u": "goatee",
        "g": "shirt",
        "b": "shirt*0.7",
        "c": "shirt",
        "n": "skin",
        "p": "pants",
        "f": "#3c2814",
    },
    head=(
        "..kkkkkk..",
        "..KKKKKK..",
        "kkkkkkkkkk",
        ".sssssssss",
        ".sGsGGsGss",
        ".sssssssss",
        ".sssuuuss.",
        "...suus...",
    ),
    torso=("gggggggg", "gbgggbgg", "gggggggg", "bbbbbbbb", "pppppppp"),
    eyes={"pts": [(7, 4), (10, 4)], "w": 1, "h": 1},
    opts={"food": "apple"},
)

biped(
    "hazmat",
    "Hazmat Partner",
    "tv",
    "A lab partner zipped into a yellow hazmat suit with a black respirator, yo.",
    slots={"suit": (255, 214, 0), "mask": (60, 60, 75), "skin": SKIN, "gloves": (70, 70, 85)},
    key={
        "y": "suit",
        "Y": "suit*0.7",
        "k": "mask",
        "G": "#8c8ca0",
        "s": "skin",
        "c": "suit",
        "n": "gloves",
        "p": "suit",
        "f": "gloves",
    },
    head=(
        "..yyyyyy..",
        ".yyyyyyyy.",
        "yyyyyyyyyy",
        "yyssssssss",
        "yyssssssss",
        "yykkkkkkky",
        ".ykkGGkky.",
        "..yyyyyy..",
    ),
    torso=("YyyyyyyY", "YyYyyYyY", "YyyyyyyY", "YyyyyyyY", "yyyyyyyy"),
    eyes={"pts": [(7, 3), (10, 3)], "w": 1, "h": 2},
    opts={"food": "apple"},
)

biped(
    "vigilante",
    "Masked Vigilante",
    "tv",
    "A masked crime-fighter: green fedora, green domino mask, long green overcoat.",
    slots={"coat": (40, 170, 90), "hat": (30, 130, 70), "mask": (20, 90, 40), "skin": SKIN},
    key={
        "g": "hat",
        "G": "hat*0.6",
        "m": "mask",
        "s": "skin",
        "S": "skin*0.8",
        "o": "coat",
        "O": "coat*0.65",
        "e": "#ffffff",
        "k": "#141414",
        "c": "coat",
        "n": "#3c3c4b",
        "p": "coat",
        "f": "#28283a",
        "w": "#f0f0f0",
    },
    head=(
        "..gggggg..",
        "..GGGGGG..",
        "gggggggggg",
        ".sssssssss",
        ".smmmmmmmm",
        ".sssssssss",
        ".ssssskss.",
        "..ssssss..",
    ),
    torso=("OowwwwoO", "OooOOooO", "OooooooO", "OoOOOOoO", "oooooooo"),
    eyes={"pts": [(7, 4), (10, 4)], "w": 1, "h": 1, "lid": "m"},
    legs=ROBE,
    opts={"food": "apple"},
)

biped(
    "chauffeur",
    "Kung-Fu Chauffeur",
    "tv",
    "A martial-arts chauffeur: black suit, peaked driver's cap and a black domino mask.",
    slots={"suit": (60, 60, 90), "cap": (45, 45, 65), "shirt": (245, 245, 255), "skin": SKIN},
    key={
        "k": "cap",
        "K": "cap*0.6",
        "h": "#1e1428",
        "m": "#141418",
        "s": "skin",
        "S": "skin*0.8",
        "j": "suit",
        "J": "suit*0.65",
        "w": "shirt",
        "e": "#ffffff",
        "c": "suit",
        "n": "skin",
        "p": "suit*0.8",
        "f": "#1e1e28",
    },
    head=(
        "..kkkkkk..",
        ".kkkkkkkk.",
        "..KKKKKKKK",
        ".hssssssss",
        ".hmmmmmmmm",
        ".sssssssss",
        ".sssssssS.",
        "..ssssss..",
    ),
    torso=("jjjwwjjj", "JjjwwjjJ", "JjjjjjjJ", "JjjjjjjJ", "pppppppp"),
    eyes={"pts": [(7, 4), (10, 4)], "w": 1, "h": 1, "lid": "m"},
    opts={"food": "apple"},
)
