"""Monsters: original pocket-monster-style creatures (chibi bipeds with an elemental attack)."""

from __future__ import annotations

from .build import biped
from .rig import Part, v

_ATK = ("attack",)

biped(
    "volt_mouse",
    "Volt Mouse",
    "monsters",
    "An electric mouse: sunny yellow, black-tipped ears, red cheeks and a lightning-bolt tail.",
    slots={"body": (255, 220, 0), "cheeks": (255, 40, 30), "tips": (40, 30, 30), "tail_base": (150, 90, 30)},
    key={
        "y": "body",
        "Y": "body*0.8",
        "r": "cheeks",
        "k": "tips",
        "u": "tail_base",
        "c": "body",
        "n": "body",
        "f": "body*0.8",
    },
    head=(
        "k........k",
        "yk......ky",
        ".yy....yy.",
        ".yyyyyyyy.",
        "yyyyyyyyyy",
        "yyyyyyyyyy",
        "yyrryyyrry",
        ".yyyyyyyy.",
    ),
    torso=("yyyyyyyy", "yyyyyyyy", "yyyyyyyy", "yyyyyyyy", "yyyyyyyy", ".YYYYYY."),
    eyes={"pts": [(7, 4), (10, 4)], "w": 1, "h": 2},
    limbs="nub",
    arms_xy=(12, 2, 9),
    feet_xy=(5, 14),
    mouth=(9, 6),
    parts={
        "tail": Part(
            0,
            2,
            {
                "default": v("..yyy", ".yyy.", "yyy..", ".yyy.", "..yy.", ".uu.."),
                "b": v(".yyy.", "yyy..", ".yyy.", "..yyy", "..yy.", ".uu.."),
                "down": v(".....", ".....", "yy...", ".yyy.", "..yy.", ".uu.."),
            },
            parent="body",
            z=-2,
        ),
    },
    opts={"food": "apple", "attack": "breath", "attack_fx": "bolt"},
    extras=_ATK,
    squash_row=11,
)

biped(
    "ember_lizard",
    "Ember Lizard",
    "monsters",
    "A fire lizard: tangerine scales, a cream belly and a flame that flickers on its tail.",
    slots={"body": (255, 118, 24), "belly": (255, 222, 130), "flame": (255, 40, 10)},
    key={
        "o": "body",
        "O": "body*0.75",
        "c": "belly",
        "r": "flame",
        "y": "#ffe600",
        "C": "body*0.7",
        "n": "body",
        "f": "body*0.8",
    },
    head=(
        "..oooooo..",
        ".oooooooo.",
        "oooooooooo",
        "oooooooooo",
        "oooooooooo",
        ".ooooooooo",
        "..oooooo..",
    ),
    head_xy=(3, 1),
    torso=("oooooooo", "ooccccoo", "ooccccoo", "ooccccoo", "ooccccoo", ".OOOOOO."),
    eyes={"pts": [(7, 4), (10, 4)], "w": 1, "h": 2},
    limbs="nub",
    arms_xy=(12, 2, 9),
    feet_xy=(5, 14),
    mouth=(11, 6),
    parts={
        "tail": Part(
            0,
            6,
            {
                "default": v("r...", "yr..", "ry..", ".oo.", "..oo", "...o"),
                "b": v(".r..", "ryr.", "yy..", ".oo.", "..oo", "...o"),
                "down": v("....", "....", "r...", "yr..", ".ooo", "...o"),
            },
            parent="body",
            z=-2,
        ),
    },
    opts={"food": "apple", "attack": "breath", "attack_fx": "fire"},
    extras=_ATK,
    squash_row=11,
)

biped(
    "bubble_turtle",
    "Bubble Turtle",
    "monsters",
    "A water turtle: sky-blue skin, big round eyes, a sturdy brown shell and a curly tail.",
    slots={"skin": (70, 170, 255), "shell": (170, 96, 40), "belly": (255, 225, 140)},
    key={
        "b": "skin",
        "B": "skin*0.75",
        "u": "shell",
        "U": "shell*0.7",
        "y": "belly",
        "c": "skin",
        "n": "skin",
        "f": "skin*0.85",
    },
    head=(
        "..bbbbbb..",
        ".bbbbbbbb.",
        "bbbbbbbbbb",
        "bbbbbbbbbb",
        "bbbbbbbbbb",
        ".bbbbbbbbb",
        "..bbbbbb..",
    ),
    head_xy=(3, 1),
    torso=("uyyyyyyu", "uyyyyyyu", "uyyyyyyu", "uyyyyyyu", "uyyyyyyu", ".uuuuuu."),
    eyes={"pts": [(6, 4), (10, 4)], "w": 2, "h": 2, "shine": True},
    limbs="nub",
    arms_xy=(12, 2, 9),
    feet_xy=(5, 14),
    mouth=(11, 6),
    parts={
        "shell": Part(
            3,
            7,
            {
                "default": v(
                    ".UUUUUUUU.", "UuuuuuuuuU", "UuuuuuuuuU", "UuuuuuuuuU", "UuuuuuuuuU", ".UUUUUUUU."
                )
            },
            parent="body",
            z=0,
        ),
        "tail": Part(
            0,
            10,
            {"default": v(".bb", "b.b", "bb."), "b": v("bb.", "b.b", ".bb"), "down": v("...", "bb.", ".bb")},
            parent="body",
            z=-2,
        ),
    },
    opts={"food": "apple", "attack": "breath", "attack_fx": "water"},
    extras=_ATK,
    squash_row=11,
)

biped(
    "sprout_toad",
    "Sprout Toad",
    "monsters",
    "A bulb toad: teal with darker spots, red eyes and a leafy bulb growing on its back.",
    slots={"skin": (70, 200, 170), "bulb": (40, 170, 60), "eyes": (255, 50, 60)},
    key={
        "t": "skin",
        "d": "skin*0.6",
        "g": "bulb",
        "G": "bulb*0.6",
        "e": "eyes",
        "m": "#0c3c28",
        "y": "skin^0.5",
        "c": "skin",
        "n": "skin",
        "f": "skin*0.8",
    },
    head=(
        "..tttttt..",
        ".tttttttt.",
        "tttttttttt",
        "tdttttttdt",
        "tttttttttt",
        ".ttmmmmtt.",
    ),
    head_xy=(3, 4),
    torso=("tttttttt", "tyyyyyyt", "tyyyyyyt", ".dttttd."),
    torso_xy=(4, 10),
    eyes={"pts": [(7, 6), (11, 6)], "w": 1, "h": 2},
    limbs="nub",
    arms_xy=(12, 2, 10),
    feet_xy=(5, 14),
    parts={
        "tail": Part(
            0,
            0,
            {
                "default": v(
                    "....gg....", "..gGGGg...", ".gGggggg..", "gGgggggGg.", "ggggGgggg.", ".ggggggg.."
                ),
                "b": v("...gg.....", "..gGGGg...", ".gGggggg..", "gGgggggGg.", "ggggGgggg.", ".ggggggg.."),
                "down": v("..........", "..gGGGg...", ".gGggggg..", "gGgggggGg.", "ggggGgggg.", ".ggggggg.."),
            },
            parent="body",
            z=-2,
        ),
    },
    opts={"food": "leaf", "attack": "breath", "attack_fx": "vine"},
    extras=_ATK,
    squash_row=12,
    lap=(8, 13),
)

_WISP = {
    "stand": v("vv.vv.vv.v", "v...v...v."),
    "walk_a": v("vvv.vv.vvv", ".v...v...v"),
    "walk_b": v("vv.vvv.vv.", "v...v...v."),
    "run_a": v("vvv.vvvv", "..v...v.", ox=1),
    "run_b": v("vv.vvv.v", ".v...v.."),
    "crouch": v("vvvvvvvvvv", ".v..v..v.."),
    "sit": v(
        "vvvvvvvvvv",
    ),
    "tuck": v(
        "v.vv.vv.v",
    ),
    "kick_back": v("vv.vv.vv", "v...v..."),
    "kick_fwd": v("vv.vv.vvv", "v...v...vv"),
}

biped(
    "grin_ghost",
    "Grin Ghost",
    "monsters",
    "A mischievous purple ghost with a jagged outline, glowing eyes and a huge toothy grin.",
    slots={"body": (150, 60, 230), "eyes": (255, 40, 80), "teeth": (255, 255, 255)},
    key={
        "v": "body",
        "V": "body*0.65",
        "W": "teeth",
        "k": "#28083c",
        "e": "eyes",
        "c": "body",
        "n": "body",
        "f": "body",
    },
    head=(
        "v...vvvv...v",
        ".vvvvvvvvvv.",
        ".vvvvvvvvvv.",
        "vvvvvvvvvvvv",
        "vvvvvvvvvvvv",
        "vvvvvvvvvvvv",
        "vvkWkWkWkWkv",
        "vvvkWkWkWkvv",
        "vvvvvvvvvvvv",
        "Vvvvvvvvvvvv",
        ".VVvvvvvvvv.",
    ),
    head_xy=(2, 1),
    torso=("",),
    torso_xy=(2, 1),
    eyes={"pts": [(5, 5), (10, 5)], "w": 2, "h": 1},
    limbs="nub",
    arms_xy=(14, 0, 8),
    feet_xy=(3, 12),
    legs=_WISP,
    opts={"food": "cookie", "attack": "breath", "attack_fx": "shadow", "sit_drop": 1},
    extras=_ATK,
    squash_row=7,
    lap=(8, 10),
)

biped(
    "puff",
    "Puff",
    "monsters",
    "A round pink puffball with huge sparkly eyes. Its attack is a lullaby.",
    slots={"body": (255, 140, 200), "eyes": (40, 110, 255), "blush": (255, 70, 120)},
    key={"p": "body", "P": "body*0.75", "r": "blush", "e": "eyes", "c": "body", "n": "body", "f": "body*0.8"},
    head=(
        "....pp.p....",
        "...pppppp...",
        ".pppppppppp.",
        "pppppppppppp",
        "pppppppppppp",
        "pppppppppppp",
        "pppppppppppp",
        "pprppppprrpp",
        ".pppppppppp.",
        "..PPPPPPPP..",
    ),
    head_xy=(2, 3),
    torso=("",),
    torso_xy=(2, 3),
    eyes={"pts": [(5, 7), (9, 7)], "w": 2, "h": 2, "shine": True},
    limbs="nub",
    arms_xy=(14, 0, 9),
    feet_xy=(4, 13),
    legs={
        "stand": v("pp....pp", "PPP..PPP"),
        "walk_a": v("pp....pp", "PPP....."),
        "walk_b": v("pp....pp", "......PPP"),
        "run_a": v(
            "PP.....PP",
        ),
        "run_b": v(
            ".PP..PP.",
        ),
        "crouch": v("PPP..PPP", oy=1),
        "sit": v("PPP..PPP", oy=1),
        "tuck": v(
            "PP....PP",
        ),
        "kick_back": v("pp..pp", "PPP.PP"),
        "kick_fwd": v("pp....pp", "PPP....PPP"),
    },
    mouth=(9, 10),
    opts={"food": "cookie", "attack": "breath", "attack_fx": "song", "sit_drop": 1},
    extras=_ATK,
    squash_row=8,
    lap=(8, 11),
)

biped(
    "drake",
    "Drake",
    "monsters",
    "A young dragon: jade scales, golden belly, cream horns and flapping wings.",
    slots={"scales": (30, 200, 140), "belly": (255, 214, 60), "wings": (0, 120, 110)},
    key={
        "g": "scales",
        "G": "scales*0.7",
        "y": "belly",
        "w": "#ffebc8",
        "m": "wings",
        "M": "wings*0.6",
        "c": "scales",
        "n": "scales",
        "f": "scales*0.8",
    },
    head=(
        ".w....w...",
        ".ww..ww...",
        "..gggggg..",
        ".gggggggg.",
        "gggggggggg",
        "gggggggggg",
        ".ggggggggG",
        "..gggggg..",
    ),
    torso=("gyyyyyyg", "gyyyyyyg", "gyyyyyyg", "gyyyyyyg", "gyyyyyyg", ".GGGGGG."),
    eyes={"pts": [(7, 4), (10, 4)], "w": 1, "h": 2},
    limbs="nub",
    arms_xy=(12, 2, 9),
    feet_xy=(5, 14),
    mouth=(11, 6),
    parts={
        "tail": Part(
            0,
            3,
            {
                "default": v("mm....", "mMm...", "mMMm..", ".mMMm.", "..mmm.", "...mm."),
                "b": v("......", "......", "mm....", "mMMm..", ".mMMmm", "..mmm."),
                "down": v("......", "......", "......", "mm....", ".mMm..", "..mmm."),
            },
            parent="body",
            z=-2,
        ),
        "tailpiece": Part(0, 11, {"default": v("g...", "gg..", ".ggg")}, parent="body", z=-1),
    },
    opts={"food": "apple", "attack": "breath", "attack_fx": "breath"},
    extras=_ATK,
    squash_row=11,
)
